### PR TITLE
Add unoccupied workspaces

### PR DESCRIPTION
**Pull request by TotalTaxAmount**
Adds the ability to show unoccupied work spaces on the eww bar with a new `-w` tag.

Example:
This:
image
To:
image

Tested on 1 & 2 monitors.
Will not break existing usage.

### CODE REVIEW

**Comment by FieldofClay** [comment]
Thanks for taking the time to work out a PR for this functionality. It looks like this adds in a workspace when an ID is missing from 1 to x, is there anything else I've missed?

I've got a jq query that does this. Is there any difference between the functionality of this PR and the jq query below?

``` bash
hyprland-workspaces _ | jq 'map(.workspaces = ([range(1; 10) 
| {active:false,class:"workspace-button w\(tostring) workspace-unoccupied",id:tonumber,name:tostring}] as $all 
| (.workspaces + $all) 
| unique_by(.id) 
| sort_by(.id | tonumber) ))'
```
Before:
``` json
[
   {
      "name": "eDP-1",
      "workspaces": [
         {
            "active": true,
            "class": "workspace-button w6 workspace-active wa6",
            "id": 6,
            "name": "6 "
         }
      ]
   }
]
```
After:
``` json
[
  {
    "name": "eDP-1",
    "workspaces": [
      {
        "active": false,
        "class": "workspace-button w1 workspace-unoccupied",
        "id": 1,
        "name": "1"
      },
      {
        "active": false,
        "class": "workspace-button w2 workspace-unoccupied",
        "id": 2,
        "name": "2"
      },
      {
        "active": false,
        "class": "workspace-button w3 workspace-unoccupied",
        "id": 3,
        "name": "3"
      },
      {
        "active": false,
        "class": "workspace-button w4 workspace-unoccupied",
        "id": 4,
        "name": "4"
      },
      {
        "active": false,
        "class": "workspace-button w5 workspace-unoccupied",
        "id": 5,
        "name": "5"
      },
      {
        "active": true,
        "class": "workspace-button w6 workspace-active wa6",
        "id": 6,
        "name": "6 "
      },
      {
        "active": false,
        "class": "workspace-button w7 workspace-unoccupied",
        "id": 7,
        "name": "7"
      },
      {
        "active": false,
        "class": "workspace-button w8 workspace-unoccupied",
        "id": 8,
        "name": "8"
      },
      {
        "active": false,
        "class": "workspace-button w9 workspace-unoccupied",
        "id": 9,
        "name": "9"
      }
    ]
  }
]
```

**Comment by TotalTaxAmount** [comment]
No problem, I was unaware of this trick with jq, however using the jq snippet you provided on a dual monitor setup give this:
```json
[
  {
    "name": "HDMI-A-1",
    "workspaces": [
      {
        "active": false,
        "class": "workspace-button w1",
        "id": 1,
        "name": "1",
        "occupied": true
      },
      {
        "active": false,
        "class": "workspace-button w2 workspace-unoccupied",
        "id": 2,
        "name": "2"
      },
      {
        "active": false,
        "class": "workspace-button w3 workspace-unoccupied",
        "id": 3,
        "name": "3"
      },
      {
        "active": false,
        "class": "workspace-button w4 workspace-unoccupied",
        "id": 4,
        "name": "4"
      },
      {
        "active": false,
        "class": "workspace-button w5 workspace-unoccupied",
        "id": 5,
        "name": "5"
      },
      {
        "active": false,
        "class": "workspace-button w6 workspace-unoccupied",
        "id": 6,
        "name": "6"
      },
      {
        "active": false,
        "class": "workspace-button w7 workspace-unoccupied",
        "id": 7,
        "name": "7"
      },
      {
        "active": false,
        "class": "workspace-button w8 workspace-unoccupied",
        "id": 8,
        "name": "8"
      },
      {
        "active": false,
        "class": "workspace-button w9 workspace-unoccupied",
        "id": 9,
        "name": "9"
      }
    ]
  },
  {
    "name": "DP-1",
    "workspaces": [
      {
        "active": false,
        "class": "workspace-button w1 workspace-unoccupied",
        "id": 1,
        "name": "1"
      },
      {
        "active": false,
        "class": "workspace-button w2 workspace-unoccupied",
        "id": 2,
        "name": "2"
      },
      {
        "active": false,
        "class": "workspace-button w3 workspace-unoccupied",
        "id": 3,
        "name": "3"
      },
      {
        "active": false,
        "class": "workspace-button w4 workspace-unoccupied",
        "id": 4,
        "name": "4"
      },
      {
        "active": false,
        "class": "workspace-button w5 workspace-unoccupied",
        "id": 5,
        "name": "5"
      },
      {
        "active": false,
        "class": "workspace-button w6 workspace-unoccupied",
        "id": 6,
        "name": "6"
      },
      {
        "active": false,
        "class": "workspace-button w7 workspace-unoccupied",
        "id": 7,
        "name": "7"
      },
      {
        "active": false,
        "class": "workspace-button w8 workspace-unoccupied",
        "id": 8,
        "name": "8"
      },
      {
        "active": false,
        "class": "workspace-button w9 workspace-unoccupied",
        "id": 9,
        "name": "9"
      },
      {
        "active": true,
        "class": "workspace-button w10 workspace-active wa10",
        "id": 10,
        "name": "10",
        "occupied": true
      },
      {
        "active": false,
        "class": "workspace-button w11",
        "id": 11,
        "name": "11",
        "occupied": true
      },
      {
        "active": false,
        "class": "workspace-button w12",
        "id": 12,
        "name": "12",
        "occupied": true
      },
      {
        "active": false,
        "class": "workspace-button w13",
        "id": 13,
        "name": "13",
        "occupied": true
      },
      {
        "active": false,
        "class": "workspace-button w18",
        "id": 18,
        "name": "18",
        "occupied": true
      }
    ]
  }
]
```

For monitor `DP-1`, it includes all the workspaces from `HDMI-A-1` aswell, which would result in the incorrect display on eww. There might be a way to change the `jq` command to account for this but I am not sure how you would go about that.

**Comment by FieldofClay** [comment]
Try this instead, it should create 10 unique workspaces on each monitor.

```
hyprland-workspaces _ | jq 'to_entries 
    | map({item: .value, counter: (.key + 1)}) 
    | map(.item.workspaces = ([range(10*.counter-9; 10*.counter+1)
    | {active:false,class:"workspace-button w\(tostring) workspace-unoccupied",id:tonumber,name:tostring}] as $all
    | (.item.workspaces + $all)
    | unique_by(.id)
    | sort_by(.id | tonumber) ))
    | map(. = .item)'
```

**Comment by FieldofClay** [comment]
@TotalTaxAmount, does the provided jq script satisfy your use case?

**Comment by TotalTaxAmount** [comment]
Sorry I completely forgot about this. Yes the jq script does work. Seems like a lot of jq to me, but it's up to you.

**Comment by FieldofClay** [comment]
Closing as can be achieved via jq.

**Pull request closed without merging**
